no:
  push:
    branches:
      - master





jobs:
  build:
    run-no: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing Printing'
        run: echo Ahmed